-- Phase 1 Tijori/CSE foundations: PDF URL column + filing brief ledger.
-- Briefs are generated by koel/briefs (AI_BRIEFS_ENABLED=0 by default).

ALTER TABLE disclosures
    ADD COLUMN IF NOT EXISTS pdf_url TEXT NULL;

CREATE TABLE IF NOT EXISTS disclosure_briefs (
    disclosure_id BIGINT PRIMARY KEY REFERENCES disclosures(id) ON DELETE CASCADE,
    status TEXT NOT NULL
        CHECK (status IN ('pending', 'ready', 'failed', 'skipped')),
    model TEXT,
    brief TEXT,
    error TEXT,
    tokens_in INT,
    tokens_out INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_disclosure_briefs_status_updated
    ON disclosure_briefs (status, updated_at);
